version: '3.9'
services:
    proxy:
        container_name: smartlook_relay_proxy
        build:
            context: .
            target: dev
        volumes:
            - ./src:/home/node/app/src:ro
        ports:
            - 80:8000
        environment:
            NODE_ENV: development
            PROXY_PORT: 8000
            # defined in .env
            LOGGER_LEVEL: ${LOGGER_LEVEL}
            RELAY_PROXY_HOST: ${RELAY_PROXY_HOST}
            MANAGER_HOST: ${MANAGER_HOST}
            WEB_SDK_WRITER_HOST: ${WEB_SDK_WRITER_HOST}
